version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://test_user:test_password@db:5432/test_db
      REDIS_URL: redis://redis:6379/0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-agent:4317
    depends_on:
      - db
      - redis
      - jaeger
    networks:
      - test_network
    ports:
      - 8000:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - test_db:/var/lib/postgresql/data
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7
    networks:
      - test_network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge