name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO: saleor
  DOCKERHUB_TAG: develop

jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 ruff pip-audit
      - name: Linting (flake8)
        run: |
          flake8  . --ignore=E501
      - name: Static Code Analysis (Ruff)
        continue-on-error: true
        run: |
          ruff check . | tee ruff-report.txt
      - name: Dependency Vulnerability Scan (pip-audit)
        run: |
          pip-audit || true   | tee pip-audit-report.txt

  