name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  
jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd saleor-api
          python -m pip install --upgrade pip
          pip install flake8 ruff pip-audit

      - name: Linting (flake8)
        run: flake8  . --ignore=E501,W503 || true

      - name: Static Code Analysis (Ruff)
        continue-on-error: true
        run: ruff check . | tee ruff-report.txt

      - name: Dependency Vulnerability Scan (pip-audit)
        run: pip-audit || true | tee pip-audit-report.txt

  build-and-deploy:
    name: Build and Deploy
    needs: check-and-lint
    runs-on: ubuntu-latest
    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
      JAEGER_AGENT_HOST: ${{ secrets.JAEGER_AGENT_HOST }}
      DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DOCKERHUB_REPO: saleor
      DOCKERHUB_TAG: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build API Image
        run: |
          cd saleor-api && docker build -t saleor-api:${{ env.DOCKERHUB_TAG }} .
        
      - name: Build Dashboard Image
        run: |
          cd saleor-dashboard && docker build -t saleor-dashboard:${{ env.DOCKERHUB_TAG }} .

      - name: Run API and Dependencies
        run: |
          docker network create saleor-backend-tier
          docker run -d --name db --network saleor-backend-tier -e POSTGRES_DB=saleor -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:15-alpine 
          docker run -d --name redis --network saleor-backend-tier redis:7.0-alpine
          docker run -d --name jaeger --network saleor-backend-tier jaegertracing/all-in-one:1.20.0
          docker run -d --name saleor-api --network saleor-backend-tier -p 8000:8000 saleor-api:${{ env.DOCKERHUB_TAG }}
          sleep 30  # Wait for API to start
          echo "Currently running containers:" && docker ps -a
      
      - name: API Health Check
        run: |
          until [[ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql) =~ ^(200|404)$ ]]; do
            echo "Waiting for Saleor API..."
            sleep 5
          done
          echo "Saleor API is healthy!"
  
      - name: Run Saleor Dashboard 
        run: |
          docker run --rm -d --name saleor-dashboard -p 9000:80 "${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard:${{ env.DOCKERHUB_TAG }}"
          sleep 10 
      
      - name: Dashboard Health Check
        run: |
          until ! curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/ | grep -E "200|404"; do
            echo "Waiting for Saleor Dashboard..."
            sleep 5
          done
          echo "Saleor Dashboard is ready!"

      - name: Trivy Scan Saleor API
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL --ignore-unfixed --no-progress saleor-api || true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      - name: Tag and Push Saleor API Docker Image
        run: |
          docker tag saleor-api:develop ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:develop
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:develop
      
      - name: Tag and Push Saleor Dashboard Docker Image
        run: |
          docker tag saleor-dashboard:develop ${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard:develop
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard:develop
          
      - name: Remove Containers
        run: |
          docker rm -f saleor-api saleor-dashboard db redis jaeger || true
          docker network rm saleor-backend-tier || true