name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_API: ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api
  DOCKER_IMAGE_DASHBOARD: ${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_TAG: develop
  DOCKERHUB_REPO: saleor
  
  
jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd saleor-api
          python -m pip install --upgrade pip
          pip install flake8 ruff pip-audit

      - name: Linting (flake8)
        run: flake8  . --ignore=E501,W503 || true

      - name: Static Code Analysis (Ruff)
        continue-on-error: true
        run: ruff check . | tee ruff-report.txt

      - name: Dependency Vulnerability Scan (pip-audit)
        run: pip-audit || true | tee pip-audit-report.txt

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: check-and-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Tag Saleor API Docker Image
        run: |
          cd saleor-api
          docker buildx build -t "${{ secrets.DOCKER_USERNAME }}/saleor-api:${{ env.DOCKERHUB_TAG }}" -f saleor-api/Dockerfile .
      - name: Build and Tag Saleor Dashboard Docker Image
        run: |
          cd saleor-dashboard
          docker buildx build -t "${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard:${{ env.DOCKERHUB_TAG }}" -f saleor-dashboard/Dockerfile .
      - name: Start Saleor API & Dashboard Containers
        run: |
          docker run -d -p 8000:8000 --name saleor-api "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-api:${{ env.DOCKERHUB_TAG }}"
          docker run -d -p 9000:80 --name salaeor-dashboard "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-dashboard:${{ env.DOCKERHUB_TAG }}"
      - name: Check Saleor API Health
        run: |
          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -E "200|404"; do
            echo "Waiting for Saleor API..."
            sleep 5
          done
          echo "Saleor API is ready!"
  
      - name: Check Saleor Dashboard Health
        run: |
            while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/ | grep -E "200|404"; do
              echo "Waiting for Saleor Dashboard..."
              sleep 5
            done
            echo "Saleor Dashboard is ready!"
      - name: Trivy Scan Saleor API
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL --ignore-unfixed --no-progress saleor-api || true
      - name: push Saleor API Docker Image
        run: |
          ddocker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-api:${{ env.DOCKERHUB_TAG }}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-dashboard:${{ env.DOCKERHUB_TAG }}"
  
      - name: Stop and Remove Containers
        run: |
          docker stop saleor-api saleor-dashboard
          docker rm saleor-api saleor-dashboard
         