name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_API: ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api
  DOCKER_IMAGE_DASHBOARD: ${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd saleor-api
          python -m pip install --upgrade pip
          pip install flake8 ruff pip-audit

      - name: Linting (flake8)
        run: flake8  . --ignore=E501,W503 || true

      - name: Static Code Analysis (Ruff)
        continue-on-error: true
        run: ruff check . | tee ruff-report.txt

      - name: Dependency Vulnerability Scan (pip-audit)
        run: pip-audit || true | tee pip-audit-report.txt

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: check-and-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          cd saleor-api
          docker build -t $DOCKER_IMAGE:develop .
          docker push $DOCKER_IMAGE:develop
    
      - name: Pull the built Docker Images
        run: |
          docker pull $DOCKER_IMAGE_API:develop
          docker pull $DOCKER_IMAGE_DASHBOARD:develop
  
      - name: Start Saleor API & Dashboard Containers
        run: |
          docker network create saleor-network

          docker run -d --name saleor-api --network saleor-network -p 8000:8000 $DOCKER_IMAGE_API:develop
          docker run -d --name saleor-dashboard --network saleor-network -p 9000:80 $DOCKER_IMAGE_DASHBOARD:develop

          sleep 10 
      - name: Check Saleor API Health
        run: |
          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -E "200|404"; do
            echo "Waiting for Saleor API..."
            sleep 5
          done
          echo "Saleor API is ready!"
  
      - name: Check Saleor Dashboard Health
        run: |
            while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/ | grep -E "200|404"; do
              echo "Waiting for Saleor Dashboard..."
              sleep 5
            done
            echo "Saleor Dashboard is ready!"
  
      - name: Stop and Remove Containers
        run: |
          docker stop saleor-api saleor-dashboard
          docker rm saleor-api saleor-dashboard
          docker network rm saleor-network