name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO: saleor
  DOCKERHUB_TAG: develop

jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 ruff pip-audit

      - name: Linting (flake8)
        run: flake8  . --ignore=E501,W503 || true

      - name: Static Code Analysis (Ruff)
        continue-on-error: true
        run: ruff check . | tee ruff-report.txt

      - name: Dependency Vulnerability Scan (pip-audit)
        run: pip-audit || true   | tee pip-audit-report.txt

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: check-and-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Tag Saleor API Docker Image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-api:${{ env.DOCKERHUB_TAG }}" ./saleor-api

      - name: Build and Tag Saleor Dashboard Docker Image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-dashboard:${{ env.DOCKERHUB_TAG }}" ./saleor-dashboard
      - name: Run containers
        run: |
          docker run -d -p 8000:8000 --name saleor-api-container "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-api:${{ env.DOCKERHUB_TAG }}"
          docker run -d -p 9000:9000 --name saleor-dashboard-container "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-dashboard:${{ env.DOCKERHUB_TAG }}"

      - name: Health Check Saleor API
        run: |
            while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -E "200|404"; do
              echo "Waiting for Saleor API..."
              sleep 5
            done
            echo "Saleor API is ready!"

      - name: Health Check Saleor Dashboard
        run: |
            while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:9000 | grep -E "200|404"; do
              echo "Waiting for Saleor Dashboard..."
              sleep 5
            done
            echo "Saleor Dashboard is ready!"
      - name: Trivy Scan Saleor API
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL --ignore-unfixed --no-progress saleor-api-app || true
      - name: push Saleor API Docker Image
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-api:${{ env.DOCKERHUB_TAG }}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}-dashboard:${{ env.DOCKERHUB_TAG }}"


  