name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request: 
    branches: [staging]

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Validate Docker Compose
        run: |
          docker compose build
          docker compose up -d --wait
          docker compose run --rm api python3 manage.py migrate
          sleep 15

      - name:  Run Health Checks
        run: |
          until curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -E "200|404"; do
            echo "Waiting for Saleor API..."
            sleep 5
          done
          echo "Saleor API is healthy!"
      - name: Stop Docker Compose
        run: docker compose -f docker-compose.yml down
  
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: compose-validate
    env:
      DOCKERHUB_REPO: saleor
      DOCKERHUB_TAG: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   
      - name: Build and Push Docker Images
        run: |
          docker buildx build --push -t "${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:${{ env.DOCKERHUB_TAG }}" -f saleor-api/Dockerfile saleor-api
      - name: Build and Tag Saleor Dashboard Docker Image
        run: |
          docker buildx build --push -t "${{ secrets.DOCKERHUB_USERNAME }}/saleor-dashboard:${{ env.DOCKERHUB_TAG }}" -f saleor-dashboard/Dockerfile saleor-dashboard
        
  