name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request: 
    branches: [staging]

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Validate Docker Compose
        run: |
          docker compose build
          docker compose run --rm api python3 manage.py migrate
          docker compose run --rm api python3 manage.py populatedb --createsuperuser
          docker compose up -d --wait
          sleep 15
          docker ps
          docker-compose ps


      - name:  Run Health Checks
        run: |
          until curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/graphql | grep -E "200|404"; do
            echo "Waiting for Saleor API..."
            sleep 5
          done
          echo "Saleor API is healthy!"
      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
  
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: compose-validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:staging .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:staging
  